name: sirup_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <=3.3.2'
dependencies:
  badges: ^2.0.3
  bitsdojo_window: ^0.1.5
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  custom_clippers: ^2.0.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  faker_dart: ^0.1.11
  file_picker: ^5.2.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  flutter_map: ^3.0.0
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.3
  hive: ^2.2.3
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  latlng: ^0.2.0
  material_design_icons_flutter: ^5.0.6996
  mobile_scanner: ^2.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  qr_flutter: ^4.0.0
  searchable_dropdown: ^1.1.3
  syncfusion_flutter_charts: ^20.3.58
  url_launcher: ^6.1.6
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/font/
    - assets/icon/
    - assets/image/
